name: Main

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  run-main-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v6
      - name: Make the script files executable
        run: chmod +x main.sh
      - name: Run the scripts
        run: ./main.sh
